# core/rainfall.py
# Rainfall metrics computed on the same water year basis as the flow products,
# so that rainfall and flow can be placed side by side on the same axis.
#
# Pairing the two is deliberate. A cumulative rainfall curve and a cumulative
# flow curve for the same water year, plotted together, depict the catchment's
# storage behaviour directly: the vertical separation between them is water that
# has fallen and not yet left the catchment.
#
# Reference for SPI
#   McKee, T.B., Doesken, N.J., Kleist, J. (1993). The relationship of drought
#   frequency and duration to time scales. 8th Conference on Applied
#   Climatology, Anaheim, 179-184.

# %%
import numpy as np
import pandas as pd
from scipy import stats

RAIN_DAY_THRESHOLD = 1.0     # mm, the conventional definition of a rain day
DRY_DAY_THRESHOLD = 1.0      # mm, below this counts as a dry day
SPI_SCALES = (3, 6, 12)      # months


# %%
def _runs(flag):
    flag = np.asarray(flag).astype(int)
    transitions = np.diff(np.concatenate(([0], flag, [0])))
    starts = np.where(transitions == 1)[0]
    ends = np.where(transitions == -1)[0] - 1
    return list(zip(starts.tolist(), ends.tolist()))


# %% annual rainfall characteristics
def annual_rainfall(dates, rain_mm, water_year_labels, complete_years,
                    rain_day_threshold=RAIN_DAY_THRESHOLD,
                    dry_day_threshold=DRY_DAY_THRESHOLD):
    """Water year rainfall totals with intensity, frequency and dry spell metrics.

    The maximum multi-day totals matter for a monsoonal catchment because runoff
    is generated by wet spells rather than by individual days, and the longest
    dry spell within the wet season is what separates a good wet from a broken
    one of the same total.
    """
    dates = pd.DatetimeIndex(dates)
    frame = pd.DataFrame({'Date': dates, 'Rain': np.asarray(rain_mm, dtype=float),
                          'WaterYear': water_year_labels})
    frame = frame[frame['WaterYear'].isin(complete_years)]

    rows = []
    for year, group in frame.groupby('WaterYear'):
        rain = group['Rain'].to_numpy()
        if not np.isfinite(rain).all():
            continue

        wet = rain >= rain_day_threshold
        dry_spells = [end - start + 1 for start, end in _runs(rain < dry_day_threshold)]

        series = pd.Series(rain)

        rows.append({
            'WaterYear': int(year),
            'Rainfall_mm': float(rain.sum()),
            'RainDays': int(wet.sum()),
            'MeanIntensity_mm': float(rain[wet].mean()) if wet.any() else 0.0,
            'Max1Day_mm': float(rain.max()),
            'Max3Day_mm': float(series.rolling(3).sum().max()),
            'Max5Day_mm': float(series.rolling(5).sum().max()),
            'LongestDrySpellDays': int(max(dry_spells)) if dry_spells else 0,
            'MeanDrySpellDays': float(np.mean(dry_spells)) if dry_spells else 0.0,
        })

    if not rows:
        return pd.DataFrame()

    return pd.DataFrame(rows).sort_values('WaterYear').reset_index(drop=True)


# %% standardised precipitation index
def _fit_spi(accumulated):
    """Gamma fit with an explicit zero probability, then map to a normal score.

    Monthly totals in a dry season are frequently exactly zero, and the gamma
    distribution is undefined at zero. The standard treatment is a mixed
    distribution: the probability of zero is estimated empirically and the gamma
    is fitted to the positive values only.
    """
    values = np.asarray(accumulated, dtype=float)
    finite = values[np.isfinite(values)]

    if finite.size < 10:
        return np.full(values.shape, np.nan)

    zero_fraction = float(np.mean(finite <= 0))
    positive = finite[finite > 0]

    if positive.size < 5 or zero_fraction >= 1.0:
        return np.full(values.shape, np.nan)

    shape, loc, scale = stats.gamma.fit(positive, floc=0)

    probability = np.where(
        values > 0,
        zero_fraction + (1.0 - zero_fraction) * stats.gamma.cdf(values, shape, loc, scale),
        0.5 * zero_fraction)

    probability = np.clip(probability, 1e-6, 1 - 1e-6)
    return stats.norm.ppf(probability)


def spi(dates, rain_mm, scales=SPI_SCALES):
    """Standardised Precipitation Index at one or more month scales.

    The distribution is fitted separately for each calendar month so that the
    index is a departure from what is normal for that month, which is essential
    in a monsoonal climate where a dry June is not a drought.
    """
    dates = pd.DatetimeIndex(dates)
    monthly = (pd.Series(np.asarray(rain_mm, dtype=float), index=dates)
               .resample('MS').sum(min_count=1))

    out = pd.DataFrame({'Month': monthly.index, 'Rainfall_mm': monthly.to_numpy()})

    for scale in scales:
        accumulated = monthly.rolling(scale).sum()
        result = pd.Series(np.nan, index=monthly.index)

        for month in range(1, 13):
            selection = accumulated.index.month == month
            values = accumulated[selection].to_numpy()
            if np.isfinite(values).sum() >= 10:
                result.loc[selection] = _fit_spi(values)

        out[f'SPI{scale}'] = result.to_numpy()

    return out


# %% cumulative curves
def cumulative_by_water_year(dates, values, water_year_labels, complete_years):
    """Cumulative total through each water year, aligned on day of water year.

    Returns a wide frame with one column per water year, indexed by day of the
    water year, which is exactly the shape the spaghetti plot needs.
    """
    dates = pd.DatetimeIndex(dates)
    frame = pd.DataFrame({'Date': dates, 'Value': np.asarray(values, dtype=float),
                          'WaterYear': water_year_labels})
    frame = frame[frame['WaterYear'].isin(complete_years)]

    columns = {}
    for year, group in frame.groupby('WaterYear'):
        cumulative = np.nancumsum(group['Value'].to_numpy())
        columns[int(year)] = pd.Series(cumulative,
                                       index=np.arange(1, len(cumulative) + 1))

    if not columns:
        return pd.DataFrame()

    wide = pd.DataFrame(columns)
    wide.index.name = 'DayOfWaterYear'
    return wide


# %% anomalies against a reference period
def annual_anomaly_series(annual, year_column, value_column,
                          reference_start=None, reference_end=None,
                          moving_windows=(10,)):
    """Departure from a reference period mean, with moving averages.

    The reference period is chosen by the user rather than being the whole
    record, because a mean taken over a record that contains a trend is not a
    stable baseline, and because comparability with published anomalies requires
    matching their reference period.
    """
    out = annual[[year_column, value_column]].copy()

    years = out[year_column].to_numpy()
    if reference_start is None:
        reference_start = int(years.min())
    if reference_end is None:
        reference_end = int(years.max())

    in_reference = (years >= reference_start) & (years <= reference_end)

    if in_reference.sum() == 0:
        reference_mean = float(out[value_column].mean())
        in_reference = np.ones(len(out), dtype=bool)
    else:
        reference_mean = float(out.loc[in_reference, value_column].mean())

    out['InReferencePeriod'] = in_reference
    out['ReferenceMean'] = reference_mean
    out['Anomaly'] = out[value_column] - reference_mean

    for window in moving_windows:
        out[f'Anomaly_MA{window}'] = (out['Anomaly']
                                      .rolling(window, center=True, min_periods=window)
                                      .mean())
        out[f'Value_MA{window}'] = (out[value_column]
                                    .rolling(window, center=True, min_periods=window)
                                    .mean())

    return out.reset_index(drop=True)
